Version 2.0.0 now packaged for 'any' architecture

diff --git a/Install b/Install
--- a/Install
+++ b/Install
@@ -1,9 +1,20 @@
 #!/bin/bash
 
 PKG_NAME="core-custom-local"
-PKG_VER="1.0.1"
 SRC="${HOME}/src"
-DEB="${SRC}/${PKG_NAME}/dist/${PKG_NAME}_${PKG_VER}.deb"
+
+[ -f "${SRC}/${PKG_NAME}/VERSION" ] || {
+  echo "Missing VERSION file: ${SRC}/${PKG_NAME}/VERSION"
+  echo "Exiting"
+  exit 1
+}
+
+. "${SRC}/${SRC_NAME}/VERSION"
+PKG_VER=${VERSION}
+PKG_REL=${RELEASE}
+PKG_PRE="${PKG_NAME}_${PKG_VER}-${PKG_REL}"
+
+DEB="${SRC}/${PKG_NAME}/dist/${PKG_PRE}.deb"
 
 [ -f "${DEB}" ] || {
     echo "$DEB not found."
